grpc:
    host: "127.0.0.1"
    port: 8888
    enable: true

psql:
    provider: "postgres"
    username: "name"
    password: "pswd"
    host: "localhost"
    port: 5432
    dbname: dbname

issuer: "sausage"

OTPHashSecretKey: "32 byte key"
JWTHashSecretKey: "32 byte key"
JWTSecretKey: "32 byte key"

AccessExp: 15m
RefreshExp: 246h

Memcache:
    host: "127.0.0.1"
    port: 8889
    enable: true