// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlacklistRefresh struct {
	RefreshHash string           `db:"refresh_hash"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
}

type Refreshlist struct {
	RefreshHash string           `db:"refresh_hash"`
	UserLogin   string           `db:"user_login"`
	UserAgent   *string          `db:"user_agent"`
	ExpiredAt   pgtype.Timestamp `db:"expired_at"`
}

type User struct {
	UserLogin    string           `db:"user_login"`
	Uuid         string           `db:"uuid"`
	OtpHash      string           `db:"otp_hash"`
	OtpLink      string           `db:"otp_link"`
	Confirmed    *bool            `db:"confirmed"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
	LastSignUpAt pgtype.Timestamp `db:"last_sign_up_at"`
}
