// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	//Confirmed
	//
	//  update users set confirmed = true where user_login = $1
	Confirmed(ctx context.Context, login *string) error
	//DeleteOldRefresh
	//
	//  delete from refreshlist where user_login = $1 and user_agent = $2 returning refresh_hash
	DeleteOldRefresh(ctx context.Context, arg DeleteOldRefreshParams) ([]string, error)
	//GetRefreshToken
	//
	//  select r.refresh_hash, (expired_at <= now()) as is_expired, r.user_agent,
	//  exists(select 1 from blacklist_refresh b where b.refresh_hash = r.refresh_hash) as block
	//  from refreshlist r where r.user_login = $1 and r.refresh_hash = $2 and r.user_agent = $3
	GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (GetRefreshTokenRow, error)
	//GetUUIDByLogin
	//
	//  select uuid from users WHERE user_login = $1
	GetUUIDByLogin(ctx context.Context, login *string) (string, error)
	//IsExist
	//
	//  select exists(select 1 from users WHERE user_login = $1)
	IsExist(ctx context.Context, login *string) (bool, error)
	//LoginByUUID
	//
	//  select user_login from users where uuid = $1
	LoginByUUID(ctx context.Context, uuid *string) (string, error)
	//OtpHash
	//
	//  select otp_hash from users where user_login = $1
	OtpHash(ctx context.Context, login *string) (string, error)
	//Register
	//
	//  insert into users (user_login, uuid, otp_hash, created_at, last_sign_up_at) values ($1, gen_random_uuid(), $2, now(), now())
	Register(ctx context.Context, arg RegisterParams) error
	//RemoveRefreshByHash
	//
	//  delete from refreshlist where refresh_hash = $1
	RemoveRefreshByHash(ctx context.Context, refreshHash *string) error
	//RemoveRefreshByLogin
	//
	//  delete from refreshlist where user_login = $1 returning refresh_hash
	RemoveRefreshByLogin(ctx context.Context, userLogin *string) ([]string, error)
	//SetBlockRefresh
	//
	//  insert into blacklist_refresh (refresh_hash) values ($1)
	SetBlockRefresh(ctx context.Context, refreshHash *string) error
	//SetRefreshHash
	//
	//  insert into refreshlist(refresh_hash, user_login, user_agent) values($1, $2, $3)
	SetRefreshHash(ctx context.Context, arg SetRefreshHashParams) error
	//UpdateLastSighUp
	//
	//  update users set last_sign_up_at = now() where user_login = $1
	UpdateLastSighUp(ctx context.Context, userLogin *string) error
}

var _ Querier = (*Queries)(nil)
