// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session.sql

package db

import (
	"context"
)

const getRefreshToken = `-- name: GetRefreshToken :one
select r.refresh_hash, (expired_at <= now()) as is_expired, r.user_agent,
exists(select 1 from blacklist_refresh b where b.refresh_hash = r.refresh_hash) as block 
from refreshlist r where r.user_login = $1 and r.refresh_hash = $2
`

type GetRefreshTokenParams struct {
	UserLogin *string `db:"user_login"`
	Hash      *string `db:"hash"`
}

type GetRefreshTokenRow struct {
	RefreshHash string  `db:"refresh_hash"`
	IsExpired   bool    `db:"is_expired"`
	UserAgent   *string `db:"user_agent"`
	Block       bool    `db:"block"`
}

// GetRefreshToken
//
//	select r.refresh_hash, (expired_at <= now()) as is_expired, r.user_agent,
//	exists(select 1 from blacklist_refresh b where b.refresh_hash = r.refresh_hash) as block
//	from refreshlist r where r.user_login = $1 and r.refresh_hash = $2
func (q *Queries) GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, arg.UserLogin, arg.Hash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.RefreshHash,
		&i.IsExpired,
		&i.UserAgent,
		&i.Block,
	)
	return i, err
}

const getUUIDByLogin = `-- name: GetUUIDByLogin :one
select uuid from users WHERE user_login = $1
`

// GetUUIDByLogin
//
//	select uuid from users WHERE user_login = $1
func (q *Queries) GetUUIDByLogin(ctx context.Context, login *string) (string, error) {
	row := q.db.QueryRow(ctx, getUUIDByLogin, login)
	var uuid string
	err := row.Scan(&uuid)
	return uuid, err
}

const removeRefreshByHash = `-- name: RemoveRefreshByHash :exec
delete from refreshlist where refresh_hash = $1
`

// RemoveRefreshByHash
//
//	delete from refreshlist where refresh_hash = $1
func (q *Queries) RemoveRefreshByHash(ctx context.Context, refreshHash *string) error {
	_, err := q.db.Exec(ctx, removeRefreshByHash, refreshHash)
	return err
}

const removeRefreshByLogin = `-- name: RemoveRefreshByLogin :exec
delete from refreshlist where user_login = $1
`

// RemoveRefreshByLogin
//
//	delete from refreshlist where user_login = $1
func (q *Queries) RemoveRefreshByLogin(ctx context.Context, userLogin *string) error {
	_, err := q.db.Exec(ctx, removeRefreshByLogin, userLogin)
	return err
}

const setBlockRefresh = `-- name: SetBlockRefresh :exec
insert into blacklist_refresh (refresh_hash) values ($1)
`

// SetBlockRefresh
//
//	insert into blacklist_refresh (refresh_hash) values ($1)
func (q *Queries) SetBlockRefresh(ctx context.Context, refreshHash *string) error {
	_, err := q.db.Exec(ctx, setBlockRefresh, refreshHash)
	return err
}

const setRefreshHash = `-- name: SetRefreshHash :exec
insert into refreshlist(refresh_hash, user_login, user_agent) values($1, $2, $3)
`

type SetRefreshHashParams struct {
	RefreshHash *string `db:"refresh_hash"`
	UserLogin   *string `db:"user_login"`
	UserAgent   *string `db:"user_agent"`
}

// SetRefreshHash
//
//	insert into refreshlist(refresh_hash, user_login, user_agent) values($1, $2, $3)
func (q *Queries) SetRefreshHash(ctx context.Context, arg SetRefreshHashParams) error {
	_, err := q.db.Exec(ctx, setRefreshHash, arg.RefreshHash, arg.UserLogin, arg.UserAgent)
	return err
}
