// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: docs/proto/v1/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	OtpCode       string                 `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AcceptRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RevokeSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mode:
	//
	//	*RevokeSessionRequest_Current_
	//	*RevokeSessionRequest_All_
	Mode          isRevokeSessionRequest_Mode `protobuf_oneof:"mode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeSessionRequest) GetMode() isRevokeSessionRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *RevokeSessionRequest) GetCurrent() *RevokeSessionRequest_Current {
	if x != nil {
		if x, ok := x.Mode.(*RevokeSessionRequest_Current_); ok {
			return x.Current
		}
	}
	return nil
}

func (x *RevokeSessionRequest) GetAll() *RevokeSessionRequest_All {
	if x != nil {
		if x, ok := x.Mode.(*RevokeSessionRequest_All_); ok {
			return x.All
		}
	}
	return nil
}

type isRevokeSessionRequest_Mode interface {
	isRevokeSessionRequest_Mode()
}

type RevokeSessionRequest_Current_ struct {
	Current *RevokeSessionRequest_Current `protobuf:"bytes,1,opt,name=current,proto3,oneof"`
}

type RevokeSessionRequest_All_ struct {
	All *RevokeSessionRequest_All `protobuf:"bytes,2,opt,name=all,proto3,oneof"`
}

func (*RevokeSessionRequest_Current_) isRevokeSessionRequest_Mode() {}

func (*RevokeSessionRequest_All_) isRevokeSessionRequest_Mode() {}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RevokeSessionRequest_Current struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest_Current) Reset() {
	*x = RevokeSessionRequest_Current{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest_Current) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest_Current) ProtoMessage() {}

func (x *RevokeSessionRequest_Current) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest_Current.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest_Current) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{4, 0}
}

func (x *RevokeSessionRequest_Current) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type RevokeSessionRequest_All struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest_All) Reset() {
	*x = RevokeSessionRequest_All{}
	mi := &file_docs_proto_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest_All) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest_All) ProtoMessage() {}

func (x *RevokeSessionRequest_All) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest_All.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest_All) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_auth_proto_rawDescGZIP(), []int{4, 1}
}

func (x *RevokeSessionRequest_All) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

var File_docs_proto_v1_auth_proto protoreflect.FileDescriptor

const file_docs_proto_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18docs/proto/v1/auth.proto\x12\aauth.v1\"'\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"$\n" +
	"\x10RegisterResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"@\n" +
	"\rAcceptRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\"(\n" +
	"\x0eAcceptResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xd4\x01\n" +
	"\x14RevokeSessionRequest\x12A\n" +
	"\acurrent\x18\x01 \x01(\v2%.auth.v1.RevokeSessionRequest.CurrentH\x00R\acurrent\x125\n" +
	"\x03all\x18\x02 \x01(\v2!.auth.v1.RevokeSessionRequest.AllH\x00R\x03all\x1a\x1d\n" +
	"\aCurrent\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x1a\x1b\n" +
	"\x03All\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05loginB\x06\n" +
	"\x04mode\"/\n" +
	"\x15RevokeSessionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xda\x01\n" +
	"\vAuthService\x12?\n" +
	"\bRegister\x12\x18.auth.v1.RegisterRequest\x1a\x19.auth.v1.RegisterResponse\x12:\n" +
	"\aConfirm\x12\x16.auth.v1.AcceptRequest\x1a\x17.auth.v1.AcceptResponse\x12N\n" +
	"\rRevokeSession\x12\x1d.auth.v1.RevokeSessionRequest\x1a\x1e.auth.v1.RevokeSessionResponseB=Z;github.com/RenterRus/sausage-profile/auth/pb/auth/v1;authpbb\x06proto3"

var (
	file_docs_proto_v1_auth_proto_rawDescOnce sync.Once
	file_docs_proto_v1_auth_proto_rawDescData []byte
)

func file_docs_proto_v1_auth_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_auth_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_auth_proto_rawDesc), len(file_docs_proto_v1_auth_proto_rawDesc)))
	})
	return file_docs_proto_v1_auth_proto_rawDescData
}

var file_docs_proto_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_docs_proto_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),              // 0: auth.v1.RegisterRequest
	(*RegisterResponse)(nil),             // 1: auth.v1.RegisterResponse
	(*AcceptRequest)(nil),                // 2: auth.v1.AcceptRequest
	(*AcceptResponse)(nil),               // 3: auth.v1.AcceptResponse
	(*RevokeSessionRequest)(nil),         // 4: auth.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),        // 5: auth.v1.RevokeSessionResponse
	(*RevokeSessionRequest_Current)(nil), // 6: auth.v1.RevokeSessionRequest.Current
	(*RevokeSessionRequest_All)(nil),     // 7: auth.v1.RevokeSessionRequest.All
}
var file_docs_proto_v1_auth_proto_depIdxs = []int32{
	6, // 0: auth.v1.RevokeSessionRequest.current:type_name -> auth.v1.RevokeSessionRequest.Current
	7, // 1: auth.v1.RevokeSessionRequest.all:type_name -> auth.v1.RevokeSessionRequest.All
	0, // 2: auth.v1.AuthService.Register:input_type -> auth.v1.RegisterRequest
	2, // 3: auth.v1.AuthService.Confirm:input_type -> auth.v1.AcceptRequest
	4, // 4: auth.v1.AuthService.RevokeSession:input_type -> auth.v1.RevokeSessionRequest
	1, // 5: auth.v1.AuthService.Register:output_type -> auth.v1.RegisterResponse
	3, // 6: auth.v1.AuthService.Confirm:output_type -> auth.v1.AcceptResponse
	5, // 7: auth.v1.AuthService.RevokeSession:output_type -> auth.v1.RevokeSessionResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_auth_proto_init() }
func file_docs_proto_v1_auth_proto_init() {
	if File_docs_proto_v1_auth_proto != nil {
		return
	}
	file_docs_proto_v1_auth_proto_msgTypes[4].OneofWrappers = []any{
		(*RevokeSessionRequest_Current_)(nil),
		(*RevokeSessionRequest_All_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_auth_proto_rawDesc), len(file_docs_proto_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_auth_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_auth_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_auth_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_auth_proto = out.File
	file_docs_proto_v1_auth_proto_goTypes = nil
	file_docs_proto_v1_auth_proto_depIdxs = nil
}
