syntax = "proto3";
package auth.v1;

option go_package = "github.com/RenterRus/sausage-profile/auth/pb/auth/v1;authpb";


message RegisterRequest {
  string login = 1;
}

message RegisterResponse{
  string url = 1;
}

message AcceptRequest {
  string login = 1;
  string otp_code = 2;
}

message AcceptResponse{
  string status = 1;
}

message RevokeSessionRequest{
  message Current{
    string hash = 1;
  }

  message All{
      string login = 1;
  }

  oneof mode{
    Current current = 1;
    All all = 2;
  }

}

message RevokeSessionResponse{
  string status = 1;
}

message ValidateTokenRequest{
  string access = 1;
}

message ValidateTokenResponse{
  string uuid = 1;
}

message Tokens{
  string access = 1;
  string refresh = 2;
}

service AuthService {

  
    rpc Register(RegisterRequest) returns (RegisterResponse);
    
    rpc Confirm(AcceptRequest) returns (AcceptResponse);

    rpc RevokeSession(RevokeSessionRequest) returns (RevokeSessionResponse);
  
    rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);

  // Login

  // RefreshToken
  
}
